// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vaccination_app.Context;

namespace vaccination_app.Migrations.Vaccine
{
    [DbContext(typeof(VaccineContext))]
    [Migration("20220519003416_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vaccination_app.VaccinationDB.Vaccine", b =>
                {
                    b.Property<int>("Child_Age")
                        .HasColumnType("int");

                    b.Property<string>("Disease_Prevention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vaccination_Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vaccine_Dose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vaccine_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Vaccine_Name")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Vaccine");
                });
#pragma warning restore 612, 618
        }
    }
}
