// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vaccination_app.Context;

namespace vaccination_app.Migrations.Staff
{
    [DbContext(typeof(StaffContext))]
    partial class StaffContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vaccination_app.VaccinationDB.Staff", b =>
                {
                    b.Property<string>("Staff_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Staff_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Staff_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staff_Role")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
